<a href="https://colab.research.google.com/github/mefy-Aruna/DIABETES_NEW/blob/main/finalDiabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing filtered data


In [1]:
import pandas as pd
# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from fancyimpute import IterativeImputer
import lightgbm as lgb
from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score


/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)


In [3]:
df = pd.read_excel(r'filtered.xlsx')
df

gender  age   bmi  waist_cm  ...  trigs  a1c  glucose.1  Diabetes 
0          1   21  18.2      82.0  ...   54.0  5.0       88.0        0.0
1          0   21  25.9      93.7  ...   83.0  5.2       88.0        0.0
2          0   21  29.5     102.3  ...  256.0  5.1        NaN        0.0
3          0   21  17.9      69.1  ...   57.0  5.1       95.0        0.0
4          0   21  30.6     101.6  ...   70.0  6.0       95.0        0.0
...      ...  ...   ...       ...  ...    ...  ...        ...        ...
5201       0   77  32.8     115.9  ...  130.0  6.5      134.0        1.0
5202       0   77  32.9     122.2  ...    NaN  6.2       98.0        0.0
5203       0   77  39.2       NaN  ...  169.0  6.3        NaN        1.0
5204       1   77  36.5     119.5  ...   67.0  6.2      103.0        0.0
5205       1   77  34.8     104.7  ...  117.0  5.7        NaN        1.0

[5206 rows x 13 columns]

In [4]:
df.to_csv('filtered.csv',index=False)


In [5]:
data = pd.read_csv(r'filtered.csv')
data

gender  age   bmi  waist_cm  ...  trigs  a1c  glucose.1  Diabetes 
0          1   21  18.2      82.0  ...   54.0  5.0       88.0        0.0
1          0   21  25.9      93.7  ...   83.0  5.2       88.0        0.0
2          0   21  29.5     102.3  ...  256.0  5.1        NaN        0.0
3          0   21  17.9      69.1  ...   57.0  5.1       95.0        0.0
4          0   21  30.6     101.6  ...   70.0  6.0       95.0        0.0
...      ...  ...   ...       ...  ...    ...  ...        ...        ...
5201       0   77  32.8     115.9  ...  130.0  6.5      134.0        1.0
5202       0   77  32.9     122.2  ...    NaN  6.2       98.0        0.0
5203       0   77  39.2       NaN  ...  169.0  6.3        NaN        1.0
5204       1   77  36.5     119.5  ...   67.0  6.2      103.0        0.0
5205       1   77  34.8     104.7  ...  117.0  5.7        NaN        1.0

[5206 rows x 13 columns]

# Imputation

In [6]:
from fancyimpute import IterativeImputer as MICE

In [7]:
from fancyimpute import IterativeImputer

In [8]:
pip install mice

  Created wheel for mice: filename=mice-0.0.1a0-cp36-none-any.whl size=1045 sha256=3c76b28ad2685e1b89763c6bf4abb929d58c089eaff3474feade319998b3a5e2
  Stored in directory: /root/.cache/pip/wheels/6c/e7/4f/1b0c52cfdb6dc95dd0ba1459459f8e4ed33cab25eccdd78d65
Successfully built mice


In [9]:
pip install fancyimpute

In [10]:
from fancyimpute import IterativeImputer

In [11]:
mice_impute = IterativeImputer()

In [12]:
mice_data = mice_impute.fit_transform(data)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarni

In [13]:
mice_data

array([[  1.        ,  21.        ,  18.2       , ...,   5.        ,
         88.        ,   0.        ],
       [  0.        ,  21.        ,  25.9       , ...,   5.2       ,
         88.        ,   0.        ],
       [  0.        ,  21.        ,  29.5       , ...,   5.1       ,
         94.16074483,   0.        ],
       ...,
       [  0.        ,  77.        ,  39.2       , ...,   6.3       ,
        106.72079006,   1.        ],
       [  1.        ,  77.        ,  36.5       , ...,   6.2       ,
        103.        ,   0.        ],
       [  1.        ,  77.        ,  34.8       , ...,   5.7       ,
         96.8663047 ,   1.        ]])

In [14]:
data_n = pd.DataFrame(mice_data)
data_n.to_csv("miceDataset.csv", index=False, header=False)

In [15]:
dfc = pd.read_csv(r'miceDataset.csv')

In [16]:
dfc

1.0  21.0  18.2        82.0  ...        54.0  5.0        88.0  0.0
0     0.0  21.0  25.9   93.700000  ...   83.000000  5.2   88.000000  0.0
1     0.0  21.0  29.5  102.300000  ...  256.000000  5.1   94.160745  0.0
2     0.0  21.0  17.9   69.100000  ...   57.000000  5.1   95.000000  0.0
3     0.0  21.0  30.6  101.600000  ...   70.000000  6.0   95.000000  0.0
4     0.0  21.0  27.9   91.000000  ...   97.000000  5.0   90.348767  0.0
...   ...   ...   ...         ...  ...         ...  ...         ...  ...
5200  0.0  77.0  32.8  115.900000  ...  130.000000  6.5  134.000000  1.0
5201  0.0  77.0  32.9  122.200000  ...  205.687652  6.2   98.000000  0.0
5202  0.0  77.0  39.2  128.090281  ...  169.000000  6.3  106.720790  1.0
5203  1.0  77.0  36.5  119.500000  ...   67.000000  6.2  103.000000  0.0
5204  1.0  77.0  34.8  104.700000  ...  117.000000  5.7   96.866305  1.0

[5205 rows x 13 columns]

In [ ]:
x = data.iloc[:, 0:65].values
y = data.iloc[:, 65].values
x
y

array([0., 0., 0., ..., 1., 0., 1.])

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)


In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
import pandas as pd
# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from fancyimpute import IterativeImputer
import lightgbm as lgb
from sklearn.model_selection import train_test_split




# LGBM

In [ ]:
lgb_clf = lgb.LGBMClassifier(random_state=0, silent=True, metric='None', n_jobs=4)


In [ ]:
lgb_clf.fit(x_train,y_train)

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               metric='None', min_child_samples=20, min_child_weight=0.001,
               min_split_gain=0.0, n_estimators=100, n_jobs=4, num_leaves=31,
               objective=None, random_state=0, reg_alpha=0.0, reg_lambda=0.0,
               silent=True, subsample=1.0, subsample_for_bin=200000,
               subsample_freq=0)

In [ ]:
y_pred = lgb_clf.predict(x_test)


In [ ]:
import pickle

In [ ]:
pickle.dump(lgb_clf, open('lgbClassifier.pkl', 'wb'))


In [ ]:
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

         0.0       0.99      0.99      0.99       893
         1.0       0.95      0.94      0.94       149

    accuracy                           0.98      1042
   macro avg       0.97      0.97      0.97      1042
weighted avg       0.98      0.98      0.98      1042



# BORUTA SELECTOR + RF

In [ ]:
from boruta import BorutaPy
from datetime import datetime
from __future__ import print_function



In [ ]:
def timer(start_time=None):
    if not start_time:
        start_time = datetime.now()
        return start_time
    elif start_time:
        thour, temp_sec = divmod((datetime.now() - start_time).total_seconds(), 3600)
        tmin, tsec = divmod(temp_sec, 60)
        print('\n Time taken: %i hours %i minutes and %s seconds.' % (thour, tmin, round(tsec, 2)))

In [ ]:
rfc = RandomForestClassifier(n_estimators=200, class_weight='balanced')

In [ ]:
boruta_selector = BorutaPy(rfc, n_estimators='auto', verbose=2)
start_time = timer(None)
boruta_selector.fit(x_train, y_train)
timer(start_time)

Iteration: 	1 / 100
Confirmed: 	0
Tentative: 	65
Rejected: 	0
Iteration: 	2 / 100
Confirmed: 	0
Tentative: 	65
Rejected: 	0
Iteration: 	3 / 100
Confirmed: 	0
Tentative: 	65
Rejected: 	0
Iteration: 	4 / 100
Confirmed: 	0
Tentative: 	65
Rejected: 	0
Iteration: 	5 / 100
Confirmed: 	0
Tentative: 	65
Rejected: 	0
Iteration: 	6 / 100
Confirmed: 	0
Tentative: 	65
Rejected: 	0
Iteration: 	7 / 100
Confirmed: 	0
Tentative: 	65
Rejected: 	0
Iteration: 	8 / 100
Confirmed: 	27
Tentative: 	12
Rejected: 	26
Iteration: 	9 / 100
Confirmed: 	27
Tentative: 	12
Rejected: 	26
Iteration: 	10 / 100
Confirmed: 	27
Tentative: 	12
Rejected: 	26
Iteration: 	11 / 100
Confirmed: 	27
Tentative: 	12
Rejected: 	26
Iteration: 	12 / 100
Confirmed: 	27
Tentative: 	12
Rejected: 	26
Iteration: 	13 / 100
Confirmed: 	27
Tentative: 	12
Rejected: 	26
Iteration: 	14 / 100
Confirmed: 	27
Tentative: 	12
Rejected: 	26
Iteration: 	15 / 100
Confirmed: 	27
Tentative: 	12
Rejected: 	26
Iteration: 	16 / 100
Confirmed: 	27
Tentative: 	

In [ ]:
data

gender  age  race  education  ...     fvc    fev1  fev1_fvc_ratio  Diabetes 
0          1   21     7        2.0  ...  3650.0  2846.0        0.779726        0.0
1          0   21     1        2.0  ...  4327.0  3629.0        0.838687        0.0
2          0   21     2        3.0  ...  4471.0  3725.0        0.833147        0.0
3          0   21     1        2.0  ...  5161.0  4301.0        0.833366        0.0
4          0   21     2        3.0  ...  6250.0  5168.0        0.826880        0.0
...      ...  ...   ...        ...  ...     ...     ...             ...        ...
5201       0   77     7        5.0  ...  3097.0  2249.0        0.726187        1.0
5202       0   77     4        3.0  ...  2872.0  1716.0        0.597493        0.0
5203       0   77     3        4.0  ...     0.0     0.0        0.000000        1.0
5204       1   77     4        2.0  ...  2060.0  1491.0        0.723786        0.0
5205       1   77     4        3.0  ...  1207.0   734.0        0.608119        1.0

[5206 rows x 66 columns]

In [ ]:
data = pd.read_csv(r'filled_Noheader.csv')
data

gender  age  race  education  ...  grip_strength   fvc  fev1  fev1_fvc_ratio
0          1   21     7          2  ...           50.3  3650  2846        0.779726
1          0   21     1          2  ...           90.1  4327  3629        0.838687
2          0   21     2          3  ...           72.7  4471  3725        0.833147
3          0   21     1          2  ...           86.6  5161  4301        0.833366
4          0   21     2          3  ...           94.4  6250  5168        0.826880
...      ...  ...   ...        ...  ...            ...   ...   ...             ...
5201       0   77     7          5  ...           65.2  3097  2249        0.726187
5202       0   77     4          3  ...            0.0  2872  1716        0.597493
5203       0   77     3          4  ...            0.0     0     0        0.000000
5204       1   77     4          2  ...           45.2  2060  1491        0.723786
5205       1   77     4          3  ...           57.4  1207   734        0.608119

[5206 rows x 65 columns]

In [ ]:
print ('\n Initial features: ', data.columns.tolist() )

# number of selected features
print ('\n Number of selected features:')
print (boruta_selector.n_features_)
feature_df = pd.DataFrame(data.columns.tolist(), columns=['features'])

feature_df['rank']=boruta_selector.ranking_
feature_df = feature_df.sort_values('rank', ascending=True).reset_index(drop=True)
print ('\n Top %d features:' % boruta_selector.n_features_)
print (feature_df.head(boruta_selector.n_features_))
feature_df.to_csv('boruta-feature-ranking.csv', index=False)

# check ranking of features
print ('\n Feature ranking:')
print (boruta_selector.ranking_)

# check selected features
print ('\n Selected features:')
print (boruta_selector.support_)

# check weak features
print ('\n Support for weak features:')
print (boruta_selector.support_weak_)

selected = data.columns[boruta_selector.support_]
train = data[selected]
data['Outcome'] = y
train.to_csv('Borutafiltered.csv',index=False)



 Initial features:  ['gender', 'age', 'race', 'education', 'marital', 'income', 'household_size', 'insurance', 'private_insur', 'gen_health', 'asthma', 'chf', 'cad', 'mi', 'cva', 'copd', 'cancer', 'diabetes', 'depression', 'hypertension', 'smoker', 'drinks_day', 'weight_kg', 'height_cm', 'bmi', 'waist_cm', 'sys_bp', 'dia_bp', 'alb_cr_ratio', 'alb', 'alt', 'ast', 'alk_phos', 'bun', 'ca', 'cpk', 't_chol', 'bicarb', 'cr', 'glucose', 'iron', 'ldh', 'phos', 't_bilirubin', 't_protein', 'u_acid', 'sodium', 'potassium', 'chloride', 'glob', 'trigs', 'wbc', 'hgb', 'hct', 'platelets', 's_cotinine', 'a1c', 'glucose.1', 'insulin', 'hdl', 'ldl_chol', 'grip_strength', 'fvc', 'fev1', 'fev1_fvc_ratio']

 Number of selected features:
27

 Top 27 features:
        features  rank
0       alk_phos     1
1             cr     1
2            bun     1
3           fev1     1
4        glucose     1
5   alb_cr_ratio     1
6         sys_bp     1
7       waist_cm     1
8            bmi     1
9      weight_kg     

In [ ]:
filtered = pd.read_csv(r'Borutafiltered.csv')
filtered

age  gen_health  diabetes  hypertension  ...  insulin  hdl   fvc  fev1
0      21           3         2             2  ...     7.27   47  3650  2846
1      21           3         2             2  ...    12.01   40  4327  3629
2      21           3         2             2  ...     0.00   38  4471  3725
3      21           4         2             2  ...     3.60   55  5161  4301
4      21           2         2             2  ...    14.58   39  6250  5168
...   ...         ...       ...           ...  ...      ...  ...   ...   ...
5201   77           2         1             2  ...    19.13   45  3097  2249
5202   77           4         1             1  ...     0.00    0  2872  1716
5203   77           5         1             1  ...     0.00   38     0     0
5204   77           3         1             1  ...    11.77   69  2060  1491
5205   77           3         1             1  ...     0.00   51  1207   734

[5206 rows x 27 columns]

In [ ]:
new_x = filtered.iloc[:, 0:26].values
new_x


array([[2.100e+01, 3.000e+00, 2.000e+00, ..., 7.270e+00, 4.700e+01,
        3.650e+03],
       [2.100e+01, 3.000e+00, 2.000e+00, ..., 1.201e+01, 4.000e+01,
        4.327e+03],
       [2.100e+01, 3.000e+00, 2.000e+00, ..., 0.000e+00, 3.800e+01,
        4.471e+03],
       ...,
       [7.700e+01, 5.000e+00, 1.000e+00, ..., 0.000e+00, 3.800e+01,
        0.000e+00],
       [7.700e+01, 3.000e+00, 1.000e+00, ..., 1.177e+01, 6.900e+01,
        2.060e+03],
       [7.700e+01, 3.000e+00, 1.000e+00, ..., 0.000e+00, 5.100e+01,
        1.207e+03]])

In [ ]:

X_t, X_val, y_t, y_val = train_test_split(new_x, y)



In [ ]:
rf2 = RandomForestClassifier( n_estimators=500, max_depth=6)
rf2.fit(X_t, y_t)
y_pred = rf2.predict(X_val)


In [ ]:
y_pred

array([0., 0., 0., ..., 0., 1., 0.])

In [ ]:
pickle.dump(rf2, open('BorutaRF.pkl', 'wb'))


In [ ]:
print(classification_report(y_val, y_pred))


              precision    recall  f1-score   support

         0.0       0.99      0.99      0.99      1111
         1.0       0.95      0.94      0.95       191

    accuracy                           0.98      1302
   macro avg       0.97      0.97      0.97      1302
weighted avg       0.98      0.98      0.98      1302



# LASSO + CrossVal

In [ ]:
from sklearn.linear_model import Lasso

In [ ]:
lasso= Lasso()


In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Ridge
parameters ={'alpha':[1]}

In [ ]:
lasso_regressor = GridSearchCV(lasso,parameters,scoring='neg_mean_squared_error',cv=5)

In [ ]:
y_pred=lasso_regressor.predict(x_test)

In [ ]:
lasso_regressor.fit(x_train,y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=Lasso(alpha=1.0, copy_X=True, fit_intercept=True,
                             max_iter=1000, normalize=False, positive=False,
                             precompute=False, random_state=None,
                             selection='cyclic', tol=0.0001, warm_start=False),
             iid='deprecated', n_jobs=None, param_grid={'alpha': [1]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='neg_mean_squared_error', verbose=0)

In [ ]:
lasso_regressor.best_score_

-0.12407344988421802

In [ ]:
#print(classification_report(y_test, y_pred))


In [ ]:
y_pred

array([0.14505283, 0.14505283, 0.14505283, ..., 0.14505283, 0.14505283,
       0.14505283])

In [ ]:
from sklearn.preprocessing import scale
from sklearn.linear_model import Lasso, LassoCV, Ridge, RidgeCV


In [ ]:
pip install sklearn

In [ ]:
from sklearn.model_selection import cross_validate


In [ ]:
from sklearn.metrics import mean_squared_error


In [ ]:
X_train, X_test , y_train, y_test = train_test_split(x, y, test_size=0.5, random_state=1)

lassocv = LassoCV(alphas=None, cv=10, max_iter=100000, normalize=True)
lassocv.fit(X_train, y_train)
lasso.set_params(alpha=lassocv.alpha_)
print("Alpha=", lassocv.alpha_)
lasso.fit(X_train, y_train)
print("mse = ",mean_squared_error(y_test, lasso.predict(X_test)))
y_pred=lassocv.predict(X_test)

Alpha= 8.592036019209137e-05
mse =  0.0508749742523064


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 50.36132967438843, tolerance: 0.03145378409527467
  positive)


In [ ]:
len(y_test)

2603

In [ ]:
len(y_pred)

7810

In [ ]:
y_new=[]
i=0

In [ ]:
for i in y_pred:
  if i>0.5:
      add=1
      y_new.append(add)
  else:
      add=0
      y_new.append(add)


In [ ]:
import numpy as np


In [ ]:
y_pred=np.asarray(y_new)

In [ ]:
#print(classification_report(y_test, y_pred))


# LOGISTIC REGRESSION + RIDGE

In [ ]:
from sklearn.linear_model import Ridge
def ridge_regression(data, predictors, alpha, models_to_plot={}):
    #Fit the model
    ridgereg = Ridge(alpha=alpha,normalize=True)
    ridgereg.fit(data[predictors],data['y'])
    y_pred = ridgereg.predict(data[predictors])
    
    #Check if a plot is to be made for the entered alpha
    if alpha in models_to_plot:
        plt.subplot(models_to_plot[alpha])
        plt.tight_layout()
        plt.plot(data['x'],y_pred)
        plt.plot(data['x'],data['y'],'.')
        plt.title('Plot for alpha: %.3g'%alpha)
    
    #Return the result in pre-defined format
    rss = sum((y_pred-data['y'])**2)
    ret = [rss]
    ret.extend([ridgereg.intercept_])
    ret.extend(ridgereg.coef_)
    return ret

In [ ]:

clf = Ridge(alpha=1.0)
clf.fit(x_train, y_train)
Ridge()

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [ ]:
y_predict=clf.predict(x_test)

In [ ]:
#accuracy_score(y_test,y_predict)

# XGBOOST

In [ ]:
import pandas as pd
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
import xgboost as xgb

train = x_train
test = x_test

# print("Train a Gradient Boosting model")
# clf = GradientBoostingClassifier(n_estimators=50, learning_rate=0.005, subsample=0.7,
#                                      min_samples_leaf=10, max_depth=7, random_state=11)
print("Train a Random Forest model")
clf = RandomForestClassifier(n_estimators=25)

clf.fit(x_train, y_train)

print("Train a XGBoost model")
params = {"objective": "reg:linear",
          "eta": 0.3,
          "max_depth": 5,
          "min_child_weight": 3,
          "silent": 1,
          "subsample": 0.7,
          "colsample_bytree": 0.7,
          "seed": 1}
num_trees=250
gbm = xgb.train(params, xgb.DMatrix(x_train, y_train), num_trees)

print("Make predictions on the test set")
test_probs = (clf.predict_proba(x_test)[:,1] +
              gbm.predict(xgb.DMatrix(x_test)))/2

y_pred= clf.predict_proba(x_test)[:, 1]


Train a Random Forest model
Train a XGBoost model
Make predictions on the test set


In [ ]:
y_pred

array([0.  , 0.2 , 0.12, ..., 0.  , 0.  , 0.  ])